In [1]:
import numpy as np

In [6]:
np.__version__

'1.26.4'

In [8]:
# create list
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [20]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
np.arange(20,10) # first element should be less than second

array([], dtype=int32)

In [28]:
n = np.arange(-20,10,5) #result can be stored in a variable called object
print(n)

[-20 -15 -10  -5   0   5]


In [31]:
np.zeros(3)  # by default dtype is float

array([0., 0., 0.])

In [32]:
np.zeros(3, dtype=int) #hyper parameter tuning 

array([0, 0, 0])

In [37]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [39]:
np.zeros((2,2)) # 2d array

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros((3,3), dtype=int) # 3d array, first number is row, second number represents columns

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
nd = np.zeros((5,9), dtype=int) #5*9 array
print(nd)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [46]:
np.size(nd) # to get the number of elements of the array

45

In [47]:
np.ones(3)  #to created 1D ones array

array([1., 1., 1.])

In [48]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [50]:
np.ones((2,2)) # create nd with ones.

array([[1., 1.],
       [1., 1.]])

In [53]:
n1 = np.ones((10,10), dtype=int)
print(n1)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [54]:
type(n1)

numpy.ndarray

In [55]:
n1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])